trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  fetchDepth: 0
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    jdkVersionOption: '1.17'
    tasks: 'clean build sonar'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'build/libs' 
    artifactName: 'drop'
    publishLocation: 'Container'