server:
  port: 8090

spring:
  jpa:
    hibernate:
      ddl-auto: update

aws:
  cognito:
    clientId: 17lthotiteoe0svo0qlhmbdm2s
    userPoolId: us-east-1_KUn4x9Gao
    region: us-east-1
    issuer: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_KUn4x9Gao
    connectionTimeout: 2000
    readTimeout: 2000
    identityPoolUrl: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_KUn4x9Gao
    jwk: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_KUn4x9Gao/.well-known/jwks.json

management:
  endpoints:
    web:
      exposure:
        include: "*"

