server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost/powerup
    username: root
    password: sasa
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  secret: ${KEYSECRET_SECURITY:ONtZp7qcsoW9eHYjFZKH$0JqjIV1Onu#eQFO0ORWXcnXVmcn0b0815cUA%%m9#it}
  expiration: ${EXPIRE_DAYS_SECURITY:3600000}

management:
  endpoints:
    web:
      exposure:
        include: "*"